# Primitive tests
type_string: "Hello World"
type_int: 123
type_float: !!float 1.0
type_double: 1.0
type_boolean: true
type_long: 9999999999

# Bukkit tests
type_location:
  world: world
  x: 100
  y: 100
  z: 100
  pitch: 90
  yaw: 15
type_material: STICK
type_sound: ENTITY_PLAYER_LEVELUP
type_world: world

# List tests
type_string_list:
  - Hello
  - World
  - Foo
  - Bar

type_sound_list:
  - ENTITY_PLAYER_LEVELUP

type_material_list:
  - STICK

type_map:
  first: Hello
  second: 123
  third: true
